//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDS_TITLECAPTION                1
#define IDS_FILEVERSION                 2
#define IDS_APPCOPYRIGHT                3
#define IDS_REGISTRYKEY                 4
#define IDC_HANDCURSOR                  100
#define IDD_NETLOGO                     101
#define IDI_MAIN                        101
#define IDD_MAIN                        102
#define IDI_PERF0                       102
#define IDI_PERF1                       103
#define IDI_PERF2                       104
#define IDI_PERF3                       105
#define IDI_PERF4                       106
#define IDI_PERF5                       107
#define IDI_PERF6                       108
#define IDI_PERF7                       109
#define IDI_PERF8                       110
#define IDI_PERF9                       111
#define IDI_PERF10                      112
#define IDI_PERF11                      113
#define IDI_PERF12                      114
#define IDI_PERF13                      115
#define IDI_PERF14                      116
#define IDI_PERF15                      117
#define IDI_PERF16                      118
#define IDI_PERF17                      119
#define IDI_PERF18                      120
#define IDI_PERF19                      121
#define IDI_PERF20                      122
#define IDI_PERF21                      123
#define IDI_PERF22                      124
#define IDI_PERF23                      125
#define IDI_PERF24                      126
#define IDI_PERF25                      127
#define IDI_PERF26                      128
#define IDI_PERF27                      129
#define IDI_PERF28                      130
#define IDI_PERF29                      131
#define IDI_PERF30                      132
#define IDI_PERF31                      133
#define IDI_PERF32                      134
#define IDI_PERF33                      135
#define IDI_PERF34                      136
#define IDI_PERF35                      137
#define IDI_PERF36                      138
#define IDI_PERF37                      139
#define IDI_PERF38                      140
#define IDI_PERF39                      141
#define IDI_PERF40                      142
#define IDI_PERF41                      143
#define IDI_PERF42                      144
#define IDI_PERF43                      145
#define IDI_PERF44                      146
#define IDI_PERF45                      147
#define IDI_PERF46                      148
#define IDI_PERF47                      149
#define IDI_PERF48                      150
#define IDI_PERF49                      151
#define IDI_PERF50                      152
#define IDI_PERF51                      153
#define IDI_PERF52                      154
#define IDI_PERF53                      155
#define IDI_PERF54                      156
#define IDI_PERF55                      157
#define IDI_PERF56                      158
#define IDI_PERF57                      159
#define IDI_PERF58                      160
#define IDI_PERF59                      161
#define IDI_PERF60                      162
#define IDI_PERF61                      163
#define IDI_PERF62                      164
#define IDI_PERF63                      165
#define IDI_PERF64                      166
#define IDI_PERF65                      167
#define IDI_PERF66                      168
#define IDI_PERF67                      169
#define IDI_PERF68                      170
#define IDI_PERF69                      171
#define IDI_PERF70                      172
#define IDI_PERF71                      173
#define IDI_PERF72                      174
#define IDI_PERF73                      175
#define IDI_PERF74                      176
#define IDI_PERF75                      177
#define IDI_PERF76                      178
#define IDI_PERF77                      179
#define IDI_PERF78                      180
#define IDI_PERF79                      181
#define IDI_PERF80                      182
#define IDI_PERF81                      183
#define IDI_PERF82                      184
#define IDI_PERF83                      185
#define IDI_PERF84                      186
#define IDI_PERF85                      187
#define IDI_PERF86                      188
#define IDI_PERF87                      189
#define IDI_PERF88                      190
#define IDI_PERF89                      191
#define IDI_PERF90                      192
#define IDI_PERF91                      193
#define IDI_PERF92                      194
#define IDI_PERF93                      195
#define IDI_PERF94                      196
#define IDI_PERF95                      197
#define IDI_PERF96                      198
#define IDI_PERF97                      199
#define IDI_PERF98                      200
#define IDI_PERF99                      201
#define IDI_PERF100                     202
#define IDC_TEXTBOX                     1000
#define IDC_NETLINK                     1000
#define IDC_OK                          1001
#define IDC_CLOSE                       1001
#define IDC_CANCEL                      1002
#define IDC_STATICTEXT                  1003
#define IDC_ABOUTICON                   1004
#define IDC_APPNAME                     1005
#define IDC_APPVERSION                  1006
#define IDC_APPCOPYRIGHT                1007
#define IDC_OKBUTTON                    1008
#define IDC_BUILDTIMEDATE               1009
#define IDC_GLLOGO                      1010
#define IDC_MEMINSTALLED                1011
#define IDC_MEMUSEDBAR                  1012
#define IDC_MEMFREEBAR                  1013
#define IDC_MEMUSED                     1014
#define IDC_MEMFREE                     1015
#define IDC_CPUUSAGE                    1016
#define IDC_CPUIDLE                     1017
#define IDC_CHECK1                      1018
#define IDC_ALWAYSONTOP                 1018
#define IDC_GRAPH                       1019
#define IDC_CPUINSTALLED                1020
#define IDC_CPUUSAGEBAR                 1021
#define IDC_CPUIDLEBAR                  1022
#define IDC_MEMUSED_LBL                 1023
#define IDC_CPUUSAGE2                   1024
#define IDC_CPUUSAGE_LBL                1024
#define IDC_CPUIDLE2                    1025
#define IDC_CPUIDLE_LBL                 1025
#define IDC_CPUUSAGEBAR2                1026
#define IDC_SYSPERFBAR                  1026
#define IDC_MEMFREE_LBL                 1026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
